version: "1"
services:

  redis: 
    image: 'redis:alpine'
    container_name: redis_c
  

  myapp:
    build: ./myapp
    container_name: myapp_web
    ports:
      - "8813:5000"
    depends_on:
      - redis