name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main



jobs:
    deploy:
      name: Deploy to EC2 on master branch push
      runs-on: ubuntu-latest
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}
      steps:
        - name: Executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST_DNS }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              ls
              cd /home/ubuntu/testt/online_shop_server_-_ci-cd
              sudo git pull
              sudo docker-compose down
              sudo docker rmi $(docker images -q)
              sudo docker-compose up --build -d
#               cd /home/ubuntu/ggg/test_git_action
#               ls
#               pwd
#               sudo git pull 
#               sudo docker-compose down
#               sudo docker rmi $(docker images -q)
#               sudo docker-compose up --build -d

